# Site settings
title: "OGGM"
description: "An open source glacier model in Python"
url: http://oggm.org
# url: http://localhost:4000  # for testing

# Secondary Parameters
baseurl: http://oggm.org
header-img: img/backgrounds/glace_t.jpg
headercolor: "#FFFFFF"
logo: img/logos/logo.png
header-images: ["img/backgrounds/slide_2.jpg", "img/backgrounds/slide_3.jpg", "img/backgrounds/slide_4.jpg", "img/backgrounds/slide_5.jpg"]

# Tertiary Parameters
github_username:  OGGM
project_repository: oggm
#disqus_shortname: oggm
#g-analytics: UA-75881392-1
#altmetric: true

# Build settings
plugins: [jekyll-watch, jekyll-assets]
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

kramdown:
  auto_ids: true

# Jekyll Settings
defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/backgrounds/dahlbreen_v1.jpg"
